### ISSUE TITLE
Erro no acesso da caixa

### ISSUE THREAD

**Issue by Jose82153** [algarves/loteria-crawlers#12]
Boa tarde.
Mais uma vez parece que a Caixa mudou de novo a API, da mesma maneira que em março deste quando você arrumou.
Não sei se mais pessoas usam, eu como uso sempre venho solicitar mais uma vez se pode arrumar.

Muito obrigado.

**Comment by algarves** [comment]
Opa, vou verificar para você e retorno o mais breve possível. Desde já, obrigado por reportar a quebra.

**Comment by algarves** [comment]
Infelizmente ando com pouco tempo para ver isso, mas brevemente identifiquei um problema no **Certificado SSL** _(que foi alterado recentemente)_ que gera uma exception e impede que consigamos requisitar o serviço correspondente. Por esse motivo parou de funcionar a lib. Mas assim que tiver um tempo melhor, irei corrigir e fechar essa Issue, ok.
