### ISSUE TITLE
Loteria Caixa

### ISSUE THREAD

**Issue by Jose82153** [algarves/loteria-crawlers#4]
Não estou conseguindo entrar mais.
Parece que o site da Caixa fez algumas mudanças.
Você pretende atualizar?
Obrigado.

**Comment by algarves** [comment]
Vou verificar a possibilidade e retorno em breve.
Obrigado por reportar.

**Comment by algarves** [comment]
@Jose82153 

Estou fechando essa Issue, pois já foi realizado o ajuste necessário para nova API das loterias da caixa.

Obrigado

**Comment by Jose82153** [comment]
Obrigado.

Em seg, 14 de mar de 2022 21:02, Khristian Algarves <
***@***.***> escreveu:
