### ISSUE TITLE
Erro nos testes

### ISSUE THREAD

**Issue by Jose82153** [algarves/loteria-crawlers#6]
Boa tarde.
Não sei se estou fazendo alguma coisa errada, mas os testes não estão funcionando.
Estou usando o NetBeans 12.5 e Java 12, por exemplo o teste de “MegasenaWebCrawlerTest” dá o seguinte erro:
“> No tests found for given includes: [com.ueby.loteria.crawlers.game.MegasenaWebCrawlerTest](--tests filter)”
Quando faço o teste no navegador entrando com o link https://servicebus2.caixa.gov.br/portaldeloterias/api/megasena/ entra o resultado atual porém não sei como fazer para uma solicitação pelo número do concurso.
Poderia mais uma vez me ajudar?
Obrigado.

**Comment by algarves** [comment]
Boa tarde,

Inicialmente o código é compilado com compatibilidade do Java 8, porém na pipeline roda todos os testes certinho com Java 11. Vou avaliar também com o Java 12 e te retorno em breve, ok.

**Comment by algarves** [comment]
@Jose82153 

Foram feitas algumas melhorias que acredito que vai te auxiliar no uso da lib, favor verificar o `README` do projeto que possui mais detalhes sobre a utilização da lib em exemplos. Caso possa ajudar em algo mais, por gentileza abrir uma nova Issue, que estarei avaliando assim que possível.

Desde já obrigado por utilizar o projeto e contribuir com sugestões, dúvidas e melhorias.
